language: go
go:
  - 1.7.x
  - 1.8.x
  - master
sudo: false

install:
  - go get -t -d -v ./...
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/fzipp/gocyclo
  - go get github.com/golang/lint/golint

script:
  - make test-full
  - make report
