name: Go

on: [push]

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Test full
      run: make test-full

# based on: github.com/koron-go/_skeleton/.github/workflows/go.yml
